[package]
name = "server"
authors = ["Himadu2000 <49078336+Himadu2000@users.noreply.github.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
async-graphql = "7.0.6"
swd = { path = "../../Rust/standard/src/swd" }
rocket = "0.5.1"
surrealdb = "1.5.3"
serde = "1.0.203"
